### PR TITLE
Integrate pickling support for the `Headers` object.

### PR DESCRIPTION
**Pull request by rt121212121**
This combined with a persisted hash of the file underlying `Headers`, can be used to load the state quickly avoiding the 4 seconds or so of delay. It is also a lot less invasive than an extension module.

### CODE REVIEW

**Review by kyuupichan — COMMENTED** [review]
Any reason the arguments to post_pickle_setup cannot be the same as __init__()?  Then you can get __init__ to call it too for the common initialisation.

**Comment by rt121212121** [comment]
I was hesitant to change `__init__`, the new version resembles what you suggested :-)

**Comment by rt121212121** [comment]
Unit test added. I think the core need from unit testing is to act as a watchdog that the pickling/unpickling works, in case the implementation accidentally breaks it. One cursory check that the restored object is the same as the original one should suffice, because at some point you are just testing the pickling concept in general.

I can't work out how to get the original headers object to release the file, so I can't call `basic_setup` as it hits a `PermissionError` in trying to open it.

**Comment by rt121212121** [comment]
Ok, should be all done.

**Pull request merged**
